"""Exercise the rulings read/write path against a throwaway file.

Every case here is a way the real Content/parcel-1991.txt could have been destroyed.
"""
import importlib.util, os, sys, tempfile, traceback

SRC = r"C:\SerialKillerGame\tools\serve-viewer.py"
spec = importlib.util.spec_from_file_location("serve_viewer", SRC)
sv = importlib.util.module_from_spec(spec)
sys.argv = ["serve-viewer.py"]           # so _port_from_argv sees no stray flags
spec.loader.exec_module(sv)

tmpdir = tempfile.mkdtemp()
sv.VERDICTS = os.path.join(tmpdir, "parcel-1991.txt")
sv.PLACES   = os.path.join(tmpdir, "placement-1991.txt")
sv.WALKS    = os.path.join(tmpdir, "roads-1991.txt")

results = []
def check(name, fn):
    try:
        fn()
        results.append(("PASS", name, ""))
    except AssertionError as e:
        results.append(("FAIL", name, str(e)))
    except Exception as e:
        results.append(("ERROR", name, f"{type(e).__name__}: {e}"))


def missing_file_is_empty_not_an_error():
    if os.path.exists(sv.VERDICTS):
        os.remove(sv.VERDICTS)
    assert sv.read_verdicts() == {}, "a missing file should read as no rulings"


def unreadable_file_raises_rather_than_looking_empty():
    # A directory where the file should be is the portable way to make open() fail with an
    # OSError that is NOT FileNotFoundError.
    path = os.path.join(tmpdir, "as-a-dir", "parcel-1991.txt")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    os.makedirs(path, exist_ok=True)
    keep, sv.VERDICTS = sv.VERDICTS, path
    try:
        try:
            sv.read_verdicts()
        except OSError:
            return                      # correct: it refused to pretend
        raise AssertionError("an unreadable file returned normally instead of raising - "
                             "this is the bug that could rewrite the file from {}")
    finally:
        sv.VERDICTS = keep


def unknown_verbs_survive_a_round_trip():
    sv.write_verdicts({
        7: {"was": "built", "kind": "dwelling"},
        9: {"was": "built", "someFutureVerb": "keep me", "footprint": "later"},
    })
    back = sv.read_verdicts()
    assert back[9].get("someFutureVerb") == "keep me", \
        f"unknown verb was dropped: {back.get(9)}"
    assert back[9].get("footprint") == "later", "footprint was dropped"
    assert back[7].get("kind") == "dwelling", "known verb was dropped"


def a_normal_single_lot_save_works():
    v = sv.read_verdicts()
    v[11] = {"was": "vacant", "kind": "", "property": "", "note": "nothing here", "footprint": ""}
    sv.write_verdicts(v)
    back = sv.read_verdicts()
    assert back[11]["was"] == "vacant", "ordinary save did not land"
    assert back[9].get("someFutureVerb") == "keep me", "an unrelated lot lost its unknown verb"


def the_cliff_guard_refuses_a_mass_deletion():
    v = {i: {"was": "built"} for i in range(1, 41)}      # 40 ruled parcels
    sv.write_verdicts(v)
    assert sv._count_ruled_parcels() == 40, "setup failed"
    try:
        sv.write_verdicts({1: {"was": "built"}})         # would drop 39 of 40
    except RuntimeError:
        after = sv._count_ruled_parcels()
        assert after == 40, f"guard raised but the file was still damaged: {after} left"
        return
    raise AssertionError("the cliff guard did NOT fire on a 40 -> 1 write")


def the_cliff_guard_allows_an_ordinary_edit():
    v = {i: {"was": "built"} for i in range(1, 41)}
    sv.write_verdicts(v)
    v[41] = {"was": "vacant"}
    sv.write_verdicts(v)                                  # 40 -> 41, must be allowed
    assert sv._count_ruled_parcels() == 41, "an ordinary addition was blocked"
    del v[41]
    sv.write_verdicts(v)                                  # 41 -> 40, one lot cleared, allowed
    assert sv._count_ruled_parcels() == 40, "clearing one lot was blocked"



# ---- the two files beside it, which carried the SAME bug verbatim ---------------------------
#
# read_verdicts was hardened after somebody worked out that one unreadable read would rewrite
# the file from an empty dict. read_places and read_walks were left with `except OSError: pass`
# untouched, and both are read-edit-write from the same POST handlers. Neither file can be
# regenerated by anything either.

def a_missing_placement_file_is_empty_not_an_error():
    if os.path.exists(sv.PLACES):
        os.remove(sv.PLACES)
    assert sv.read_places() == {}, "a missing overlay should read as no adjustments"


def an_unreadable_placement_file_raises():
    path = os.path.join(tmpdir, "a-directory-not-a-file")
    os.makedirs(path, exist_ok=True)
    keep, sv.PLACES = sv.PLACES, path
    try:
        try:
            sv.read_places()
        except OSError:
            return
        raise AssertionError("an unreadable placement file must RAISE, not read as empty - "
                             "the POST handler writes whatever this returns straight back")
    finally:
        sv.PLACES = keep


def the_placement_cliff_guard_refuses_a_mass_deletion():
    full = {f"{i}|0": {"dx": 1.0, "dy": 2.0, "turn": 0.0} for i in range(40)}
    sv.write_places(full)
    try:
        sv.write_places({"1|0": {"dx": 1.0, "dy": 2.0, "turn": 0.0}})
    except RuntimeError:
        assert len(sv.read_places()) == 40, "nothing may be lost when the guard fires"
        return
    raise AssertionError("dropping 40 placed buildings to 1 must be refused")


def the_placement_cliff_guard_allows_an_ordinary_edit():
    full = {f"{i}|0": {"dx": 1.0, "dy": 2.0, "turn": 0.0} for i in range(40)}
    sv.write_places(full)
    full["7|0"] = {"dx": 9.0, "dy": 9.0, "turn": 45.0}
    sv.write_places(full)
    assert abs(sv.read_places()["7|0"]["turn"] - 45.0) < 0.01, "an ordinary edit must go through"


def a_missing_walks_file_is_empty_not_an_error():
    if os.path.exists(sv.WALKS):
        os.remove(sv.WALKS)
    assert sv.read_walks()["roads"] == {}, "a missing file should read as no walk rulings"


def an_unreadable_walks_file_raises():
    path = os.path.join(tmpdir, "another-directory")
    os.makedirs(path, exist_ok=True)
    keep, sv.WALKS = sv.WALKS, path
    try:
        try:
            sv.read_walks()
        except OSError:
            return
        raise AssertionError("an unreadable roads-1991.txt must RAISE, not read as empty")
    finally:
        sv.WALKS = keep


def the_walks_cliff_guard_refuses_a_mass_deletion():
    side = sorted(sv.WALK_SIDES)[0]
    full = {"roads": {f"street{i}": side for i in range(40)},
            "blocks": {}, "was": {}, "wasBlocks": {}}
    sv.write_walks(full)
    try:
        sv.write_walks({"roads": {"street1": side}, "blocks": {}, "was": {}, "wasBlocks": {}})
    except RuntimeError:
        assert len(sv.read_walks()["roads"]) == 40, "nothing may be lost when the guard fires"
        return
    raise AssertionError("dropping 40 walk rulings to 1 must be refused")


for name, fn in [
    ("missing file reads as empty, not an error", missing_file_is_empty_not_an_error),
    ("unreadable file RAISES instead of looking empty", unreadable_file_raises_rather_than_looking_empty),
    ("unknown verbs survive a round trip", unknown_verbs_survive_a_round_trip),
    ("an ordinary single-lot save works", a_normal_single_lot_save_works),
    ("the cliff guard refuses a mass deletion", the_cliff_guard_refuses_a_mass_deletion),
    ("the cliff guard allows ordinary edits", the_cliff_guard_allows_an_ordinary_edit),
    ("placement: missing file reads as empty", a_missing_placement_file_is_empty_not_an_error),
    ("placement: unreadable file RAISES", an_unreadable_placement_file_raises),
    ("placement: cliff guard refuses mass deletion", the_placement_cliff_guard_refuses_a_mass_deletion),
    ("placement: cliff guard allows ordinary edits", the_placement_cliff_guard_allows_an_ordinary_edit),
    ("roads-1991: missing file reads as empty", a_missing_walks_file_is_empty_not_an_error),
    ("roads-1991: unreadable file RAISES", an_unreadable_walks_file_raises),
    ("roads-1991: cliff guard refuses mass deletion", the_walks_cliff_guard_refuses_a_mass_deletion),
]:
    check(name, fn)

width = max(len(n) for _, n, _ in results)
bad = 0
for status, name, detail in results:
    print(f"  {status:5}  {name.ljust(width)}  {detail}")
    if status != "PASS":
        bad += 1
print()
print(f"{len(results) - bad}/{len(results)} passed")
sys.exit(1 if bad else 0)
